version: 2.1

parameters:
  my_parameter:
    type: boolean
    default: true    

workflows:
  general-workflow:
    jobs:
      - build
      # - unit-test
      # - jacoco-test
      # - checkstyle
      # - dependencycheck

jobs:
  build:    
    docker:
      - image: cimg/openjdk:17.0.6    
    steps:
      - run: echo "Running tests"
      - run: echo "My parameter is:"<< pipeline.parameters.my_parameter >>
    # when: <<${my_parameter} == true>>
      