version: 2.1

workflows:
  general-workflow:
    jobs:
      - build




jobs:
  build:    
    docker:
      - image: cimg/openjdk:17.0.6    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: chmod +x gradlew

      - run: gradl build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
