version: 2.1

workflows:
  general-workflow:
    jobs:
      - build
      # - unit-test
      # - jacoco-test
      # - checkstyle
      # - dependencycheck
      - sonarqube




jobs:
  build:    
    docker:
      - image: cimg/openjdk:17.0.6    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle build -x test -x check

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  unit-test:
    docker:
      - image: cimg/openjdk:17.0.6
    steps:
      - checkout
      - when:
          condition:
            equal: [ "true", "true" ]
          steps:
            - run: gradle test
  jacoco-test:
    docker:
    - image: cimg/openjdk:17.0.6
    steps:
    - checkout
    - when:
          condition:
            equal: [ "true", "false" ]
          steps:
            - run: gradle jacocoTestReport

  checkstyle:
    docker:
    - image: cimg/openjdk:17.0.6
    steps:
    - checkout
    # - run: wget -p 

  dependencycheck:
    docker:
    - image: cimg/openjdk:17.0.6
    steps:
    - checkout

    # - run: gradle dependencyCheckAnalyze
    
  sonarqube:
    working_directory: ~/repo
    docker:
    - image: cimg/openjdk:17.0.6
    steps:
    - checkout
    - run: rm -rf ~/repo
    - run:
        name: Install SonarScanner
        command: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          
    # - run: ls
    - run: 
        command: |
          ls
          cd ~/repo/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin
          ls
    # - run: ls
    # - run: sonar-scanner/bin/
    # - run: ls
