version: 2.1

parameters:
  my_parameter:
    type: boolean
    default: false    

workflows:
  general-workflow:
    jobs:
      - build
      # - unit-test
      # - jacoco-test
      # - checkstyle
      # - dependencycheck

jobs:
  build:    
    docker:
      - image: cimg/openjdk:17.0.6    
    steps:
      - run: echo "Running tests"
      # - run: echo "My parameter is:"<< pipeline.parameters.my_parameter >>
      - when:
          condition: << pipeline.parameters.my_parameter >>
          steps:
            - run: echo "my custom checkout"
      