version: 2.1

workflows:
  general-workflow:
    jobs:
      - build
      - unit-test
      - jacoco-test




jobs:
  build:    
    docker:
      - image: cimg/openjdk:17.0.6    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle build -x test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  unit-test:
    docker:
      - image: cimg/openjdk:17.0.6
    steps:
      - checkout

      - run: gradle test
  jacoco-test:
    docker:
    - image: cimg/openjdk:17.0.6
    steps:
    - checkout

    - run: gradle jacocoTestReport