version: 2.1

workflows:
  general-workflow:
    jobs:
      - build
      # - unit-test
      # - jacoco-test
      # - checkstyle
      # - dependencycheck




jobs:
  build:
    parameters:
      my_parameter:
        type: boolean
        default: true    
    docker:
      - image: cimg/openjdk:17.0.6    
    steps:
      - run: echo "Running tests"
      - run: echo "My parameter is:"${my_parameter}
    # when: <<${my_parameter} == true>>
      